import {useMemo,useState} from "react";
import {Activity,Archive,ArrowUpRight,Bell,BookOpen,CheckCircle2,ChevronDown,Clock3,Command,Filter,Inbox,LayoutDashboard,Menu,MessageSquare,Paperclip,Plus,Search,Send,Settings,Sparkles,Tag,Users,X,Zap} from "lucide-react";
import {Area,AreaChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";

type Ticket={id:string;name:string;company:string;subject:string;preview:string;priority:"Urgent"|"High"|"Normal";status:"Open"|"Pending"|"Resolved";time:string;channel:"Email"|"Chat";tag:string};
const tickets:Ticket[]=[
{id:"#4821",name:"Maya Chen",company:"Northstar Labs",subject:"Unable to update billing details",preview:"Hi team, I keep getting an error when I try to update...",priority:"Urgent",status:"Open",time:"4 min",channel:"Email",tag:"Billing"},
{id:"#4818",name:"Daniel Brooks",company:"Atlas Health",subject:"API authentication failing",preview:"Our production API started returning 401 responses this morning.",priority:"High",status:"Open",time:"18 min",channel:"Chat",tag:"Technical"},
{id:"#4815",name:"Amelia Ross",company:"Cobalt Studio",subject:"How do I change my plan?",preview:"I'd like to move our workspace to the Pro plan.",priority:"Normal",status:"Pending",time:"42 min",channel:"Email",tag:"Account"},
{id:"#4810",name:"Noah Williams",company:"Vertex Commerce",subject:"Webhook delivery delay",preview:"We're seeing delayed webhook events for recent orders.",priority:"High",status:"Open",time:"1 hr",channel:"Chat",tag:"Technical"},
{id:"#4802",name:"Olivia Patel",company:"Brightline Legal",subject:"Invoice question",preview:"Could you explain the extra charge on our latest invoice?",priority:"Normal",status:"Resolved",time:"3 hrs",channel:"Email",tag:"Billing"},
{id:"#4797",name:"Ethan Cole",company:"Pioneer Finance",subject:"Password reset link expired",preview:"The reset link from yesterday is no longer working.",priority:"Normal",status:"Resolved",time:"Yesterday",channel:"Email",tag:"Account"}];
const trend=[{n:"Mon",v:31},{n:"Tue",v:44},{n:"Wed",v:39},{n:"Thu",v:55},{n:"Fri",v:48},{n:"Sat",v:63},{n:"Sun",v:71}];
const nav=[["Overview",LayoutDashboard],["Inbox",Inbox],["Customers",Users],["Knowledge Base",BookOpen],["Analytics",Activity]] as const;

export default function App(){
const[section,setSection]=useState("Overview"),[selected,setSelected]=useState(tickets[0]),[query,setQuery]=useState(""),[filter,setFilter]=useState("All"),[mobile,setMobile]=useState(false),[ai,setAi]=useState(false);
const filtered=useMemo(()=>tickets.filter(t=>(filter==="All"||t.status===filter)&&Object.values(t).join(" ").toLowerCase().includes(query.toLowerCase())),[query,filter]);
return <div className="app"><aside className={mobile?"sidebar open":"sidebar"}><div className="brand"><span className="brand-mark"><Sparkles size={16}/></span>Resolve<span className="muted">AI</span></div><div className="agent"><span>TE</span><div><b>Taiwo Emmanuel</b><small>Support Agent · Online</small></div><i/></div><nav>{nav.map(([name,I])=><button key={name} className={section===name?"nav active":"nav"} onClick={()=>{setSection(name);setMobile(false)}}><I size={17}/>{name}{name==="Inbox"&&<em>12</em>}</button>)}</nav><p className="label">WORKSPACE</p><button className="nav"><Zap size={17}/>Automations</button><button className="nav"><Tag size={17}/>Tags</button><button className="nav"><Settings size={17}/>Settings</button><div className="bottom"><div className="ai-card"><Sparkles size={17}/><div><b>AI Copilot</b><small>Ready to assist</small></div><i/></div></div></aside>{mobile&&<div className="backdrop" onClick={()=>setMobile(false)}/>}<main className="main"><header><button className="mobile" onClick={()=>setMobile(true)}><Menu/></button><div className="crumb"><Command size={14}/> / {section}</div><div className="tools"><div className="search"><Search size={15}/><input placeholder="Search tickets, customers..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><button className="bell"><Bell size={17}/><i/></button><span className="profile">TE</span></div></header><div className="content">{section==="Overview"?<Overview onAI={()=>setAi(true)}/>:section==="Inbox"?<InboxView filtered={filtered} selected={selected} setSelected={setSelected} filter={filter} setFilter={setFilter}/>:<Module section={section} onAI={()=>setAi(true)}/>}</div></main>{ai&&<Assistant close={()=>setAi(false)} ticket={selected}/>}</div>}

function Overview({onAI}:{onAI:()=>void}){return <><div className="page-head"><div><p className="eyebrow">MONDAY, SEPTEMBER 28, 2026</p><h1>Good morning, Taiwo</h1><p className="sub">Here is your support team's pulse for today.</p></div><button className="primary" onClick={onAI}><Sparkles size={15}/> Ask AI Copilot</button></div><div className="metrics">{[["Open tickets","28","+8.2%",Inbox],["Avg. first response","18m","-12.4%",Clock3],["Resolved today","42","+16.7%",CheckCircle2],["CSAT","96.4%","+2.1%",Zap]].map(([a,b,c,I])=><div className="metric" key={String(a)}><div className="metric-top"><span>{a}</span><strong><I size={16}/></strong></div><h2>{b}</h2><small>{c} <span>vs last week</span></small></div>)}</div><div className="layout"><section className="card chart-card"><div className="card-head"><div><h2>Tickets resolved</h2><p>Resolution volume over the last 7 days</p></div><button className="select">This week <ChevronDown size={13}/></button></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><XAxis dataKey="n" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="v" strokeWidth={3} fillOpacity={.12}/></AreaChart></ResponsiveContainer></div></section><section className="card queue"><div className="card-head"><div><h2>Needs attention</h2><p>Priority queue</p></div><span className="urgent">4 urgent</span></div>{tickets.slice(0,4).map(t=><button className="queue-item" key={t.id}><span className={"dot "+t.priority.toLowerCase()}/><div><b>{t.subject}</b><small>{t.name} · {t.time}</small></div><ArrowUpRight size={14}/></button>)}</section></div><section className="card"><div className="card-head pad"><div><h2>Recent tickets</h2><p>Latest customer conversations</p></div><button className="link">Open inbox <ArrowUpRight size={13}/></button></div><TicketTable data={tickets.slice(0,5)}/></section><div className="copilot-banner"><div className="ai-icon"><Sparkles size={20}/></div><div><b>AI Copilot is ready</b><p>Summarize tickets, identify urgent conversations, and draft customer replies.</p></div><button className="secondary" onClick={onAI}>Open Copilot</button></div></>}

function InboxView({filtered,selected,setSelected,filter,setFilter}:{filtered:Ticket[];selected:Ticket;setSelected:(t:Ticket)=>void;filter:string;setFilter:(s:string)=>void}){return <div className="inbox-layout"><section className="card ticket-list"><div className="inbox-head"><div><h1>Support Inbox</h1><p>{filtered.length} conversations</p></div><button className="primary"><Plus size={15}/> New ticket</button></div><div className="filterbar"><button className="filter"><Filter size={14}/></button>{["All","Open","Pending","Resolved"].map(s=><button key={s} className={filter===s?"chip selected":"chip"} onClick={()=>setFilter(s)}>{s}</button>)}</div><div className="ticket-items">{filtered.map(t=><button key={t.id} onClick={()=>setSelected(t)} className={selected.id===t.id?"ticket selected":"ticket"}><div className="ticket-top"><b>{t.name}</b><time>{t.time}</time></div><strong>{t.subject}</strong><p>{t.preview}</p><div><em className={"priority "+t.priority.toLowerCase()}>{t.priority}</em><span className="ticket-tag">{t.tag}</span><span className="channel">{t.channel}</span></div></button>)}</div></section><Conversation ticket={selected}/></div>}

function TicketTable({data}:{data:Ticket[]}){return <div className="table-wrap"><table><thead><tr><th>Customer</th><th>Subject</th><th>Priority</th><th>Status</th><th>Updated</th></tr></thead><tbody>{data.map(t=><tr key={t.id}><td><b>{t.name}</b><small>{t.company}</small></td><td><b>{t.subject}</b><small>{t.id}</small></td><td><em className={"priority "+t.priority.toLowerCase()}>{t.priority}</em></td><td><em className={"status "+t.status.toLowerCase()}>{t.status}</em></td><td><small>{t.time}</small></td></tr>)}</tbody></table></div>}

function Conversation({ticket}:{ticket:Ticket}){const[text,setText]=useState("");return <section className="card conversation"><div className="conversation-head"><div><p className="eyebrow">{ticket.id} · {ticket.channel}</p><h2>{ticket.subject}</h2><span>{ticket.name} · {ticket.company}</span></div><button className="secondary"><Archive size={14}/> Close</button></div><div className="messages"><div className="msg customer"><span>MC</span><div><b>{ticket.name}</b><small>10:14 AM</small><p>{ticket.preview} We need this fixed before our next invoice is generated.</p></div></div><div className="msg agent"><span>TE</span><div><b>You</b><small>10:22 AM</small><p>Thanks for reporting this. I'm checking the account and will keep you updated here.</p></div></div></div><div className="reply-tools"><button onClick={()=>setText("Hi "+ticket.name+", thanks for reaching out. I've reviewed your request and I'm looking into this now.")}><Sparkles size={14}/> AI draft</button><button><Paperclip size={14}/> Attach</button></div><div className="composer"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Write a reply to the customer..."/><div><span>Public reply</span><button><Send size={15}/> Send</button></div></div></section>}

function Assistant({close,ticket}:{close:()=>void;ticket:Ticket}){return <aside className="drawer"><div className="drawer-head"><b><span className="ai-dot"><Sparkles size={14}/></span>AI Support Copilot</b><button onClick={close}><X size={18}/></button></div><div className="ai-intro"><div className="ai-big"><Sparkles/></div><h2>How can I help?</h2><p>Analyze conversations, summarize tickets and draft accurate customer replies.</p></div><div className="context"><small>ACTIVE TICKET</small><b>{ticket.id} · {ticket.subject}</b></div><div className="prompts">{["Summarize this ticket","Draft a helpful reply","Find similar resolved tickets","What should I do next?"].map(x=><button key={x}><MessageSquare size={14}/>{x}<ArrowUpRight size={13}/></button>)}</div><div className="chat"><input placeholder="Ask your support copilot..."/><button><Send size={15}/></button></div></aside>}

function Module({section,onAI}:{section:string;onAI:()=>void}){return <div className="module card"><div><div className="ai-big"><Sparkles/></div><h1>{section}</h1><p>This module is ready for authenticated API data, permissions, filters and workflow actions.</p><button className="primary" onClick={onAI}><Sparkles size={15}/> Open AI Copilot</button></div></div>}
